cShareSystems.load_pas("Academia Teams", [
    "coui://ui/mods/academia/systems/academioe_5v5.pas",
	"coui://ui/mods/academia/systems/academius_5v5.pas",
    "coui://ui/mods/academia/systems/floataurius_5v5 astroid 10 mins.pas",
    "coui://ui/mods/academia/systems/floataurius_5v5.pas",
    "coui://ui/mods/academia/systems/hilarioe_5v5 astroid 10 mins.pas",
    "coui://ui/mods/academia/systems/hilarioe_5v5 no astroids.pas",
    "coui://ui/mods/academia/systems/hilarioe_5v5.pas",
	"coui://ui/mods/academia/systems/kaixo_6v6.pas",
	"coui://ui/mods/academia/systems/pokeball_4v4.pas",
	"coui://ui/mods/academia/systems/stirix_4v4.pas",
	"coui://ui/mods/academia/systems/stirix-duo_4v4.pas",
"coui://ui/mods/academia/systems/tianion_4v4.pas",
"coui://ui/mods/academia/systems/xaxium-4_7v7.pas",
"coui://ui/mods/academia/systems/xu'er-a_5v5.pas",
"coui://ui/mods/academia/systems/xu'er-s_5v5.pas",
"coui://ui/mods/academia/systems/zeptune-1_10v10.pas",
"coui://ui/mods/academia/systems/zyion-alpha_8v8.pas",
"coui://ui/mods/academia/systems/zypherium_8v8.pas",
"coui://ui/mods/academia/systems/zypherium_duo 8v8.pas",
"coui://ui/mods/academia/systems/toxicitiy-tri_5v5.pas",
"coui://ui/mods/academia/systems/toxicitiy-tri_6v6.pas",
"coui://ui/mods/academia/systems/toxicitiy-tri_7v7.pas",
"coui://ui/mods/academia/systems/digix_5v5.pas",
"coui://ui/mods/academia/systems/toxicitiy_5v5.pas",
"coui://ui/mods/academia/systems/toxicitiy-a_5v5.pas",
"coui://ui/mods/academia/systems/toxicitiy-duo_5v5.pas",
"coui://ui/mods/academia/systems/sylphium_5v5.pas",
"coui://ui/mods/academia/systems/kokoro_5v5.pas",
"coui://ui/mods/academia/systems/kra'z_5v5.pas",
"coui://ui/mods/academia/systems/ocean'rae_(water) 5v5.pas",
"coui://ui/mods/academia/systems/prime_5v5.pas",
"coui://ui/mods/academia/systems/ancients_4v4.pas",
"coui://ui/mods/academia/systems/archon_(isolated water) 5v5.pas",
"coui://ui/mods/academia/systems/archon_smiley (isolated water) 5v5.pas",
"coui://ui/mods/academia/systems/archon_smiley-m 5v5.pas",
"coui://ui/mods/academia/systems/archon-m_5v5.pas",
"coui://ui/mods/academia/systems/bra'x_5v5.pas",
"coui://ui/mods/academia/systems/tranquil_5v5.pas",
"coui://ui/mods/academia/systems/tranquil-exrtra_5v5.pas",
"coui://ui/mods/academia/systems/tranquil-semi_5v5.pas",
"coui://ui/mods/academia/systems/aca's_universe - s.pas",
"coui://ui/mods/academia/systems/aca's_universe trio.pas",
"coui://ui/mods/academia/systems/aca's_universe.pas",
"coui://ui/mods/academia/systems/devil's_peak 5v5.pas",
"coui://ui/mods/academia/systems/ori'calcum_5v5.pas",
"coui://ui/mods/academia/systems/arayk_5v5.pas",
"coui://ui/mods/academia/systems/dystopia_10v10.pas",
"coui://ui/mods/academia/systems/mel'_5v5.pas",
"coui://ui/mods/academia/systems/mix'ii_10v10.pas",
"coui://ui/mods/academia/systems/monk's_temple 5v5.pas",
"coui://ui/mods/academia/systems/naef_9v9.pas",
"coui://ui/mods/academia/systems/xi'ii_7v7.pas",
"coui://ui/mods/academia/systems/ori'leo_5v5.pas",
"coui://ui/mods/academia/systems/dystopia-m_10v10.pas",
"coui://ui/mods/academia/systems/tai'jin_10v10.pas",
"coui://ui/mods/academia/systems/honeypot_10v10.pas",
"coui://ui/mods/academia/systems/hilarius_10v10.pas",
"coui://ui/mods/academia/systems/se'terra_6v6.pas",
"coui://ui/mods/academia/systems/dyr'ii_6v6.pas",
"coui://ui/mods/academia/systems/sil'naria_7v7.pas",
"coui://ui/mods/academia/systems/sil'naria-m_7v7.pas",
"coui://ui/mods/academia/systems/cinder'ea_1v1 - 13v13.pas",
"coui://ui/mods/academia/systems/iron_throne 1v1 - 15v15.pas",
"coui://ui/mods/academia/systems/millenium'f_1v1 - 14v14.pas",
"coui://ui/mods/academia/systems/mazii'_1v1 - 12v12.pas",
"coui://ui/mods/academia/systems/hilarius-m_1v1 - 12v12.pas",
"coui://ui/mods/academia/systems/dystopia-m_1v1 - 10v10.pas",
"coui://ui/mods/academia/systems/tai'jin_1v1 - 10v10.pas",
"coui://ui/mods/academia/systems/se'terra_1v1 - 6v6.pas",
"coui://ui/mods/academia/systems/devil's_peak 1v1 - 5v5.pas",
"coui://ui/mods/academia/systems/exos_1v1 - 8v8.pas",
"coui://ui/mods/academia/systems/apex_1v1 - 8v8.pas"
]);
