cShareSystems.load_pas("Academia Teams", [
    "coui://ui/mods/academia/systems/academioe_5v5.pas",
	"coui://ui/mods/academia/systems/academius_5v5.pas",
    "coui://ui/mods/academia/systems/floataurius_5v5 astroid 10 mins.pas",
    "coui://ui/mods/academia/systems/floataurius_5v5.pas",
    "coui://ui/mods/academia/systems/hilarioe_5v5 astroid 10 mins.pas",
    "coui://ui/mods/academia/systems/hilarioe_5v5 no astroids.pas",
    "coui://ui/mods/academia/systems/hilarioe_5v5.pas",
	"coui://ui/mods/academia/systems/kaixo_6v6.pas",
	"coui://ui/mods/academia/systems/pokeball_4v4.pas",
	"coui://ui/mods/academia/systems/stirix_4v4.pas",
	"coui://ui/mods/academia/systems/stirix-duo_4v4.pas",
"coui://ui/mods/academia/systems/tianion_4v4.pas",
"coui://ui/mods/academia/systems/xaxium-4_7v7.pas",
"coui://ui/mods/academia/systems/xu'er-a_5v5.pas",
"coui://ui/mods/academia/systems/xu'er-s_5v5.pas",
"coui://ui/mods/academia/systems/zeptune-1_10v10.pas",
"coui://ui/mods/academia/systems/zyion-alpha_8v8.pas",
"coui://ui/mods/academia/systems/zypherium_8v8.pas",
"coui://ui/mods/academia/systems/zypherium_duo 8v8.pas",
"coui://ui/mods/academia/systems/toxicitiy-tri_5v5.pas",
"coui://ui/mods/academia/systems/toxicitiy-tri_6v6.pas",
"coui://ui/mods/academia/systems/toxicitiy-tri_7v7.pas"
"coui://ui/mods/academia/systems/digix_5v5.pas",
"coui://ui/mods/academia/systems/toxicitiy_5v5.pas",
"coui://ui/mods/academia/systems/toxicitiy-a_5v5.pas",
"coui://ui/mods/academia/systems/toxicitiy-duo_5v5.pas"
]);
